const std = @import("std");

/// Generates a Zig file containing a pub list of all suite names in the test suite.
fn generateSuiteNamesZig(b: *std.Build) ![]const u8 {
    var names: std.ArrayListUnmanaged([]const u8) = .{};
    defer {
        for (names.items) |name| b.allocator.free(name);
        names.deinit(b.allocator);
    }

    var maybe_dir = std.fs.cwd().openDir("test_suite/v1", .{ .iterate = true }) catch |err| switch (err) {
        error.FileNotFound => null,
        else => return err,
    };
    if (maybe_dir) |*dir| {
        defer dir.close();
        var it = dir.iterate();
        while (try it.next()) |entry| {
            if (entry.kind != .file) continue;
            if (!std.mem.endsWith(u8, entry.name, ".json.gz")) continue;
            const suite_name = entry.name[0 .. entry.name.len - ".json.gz".len];
            if (std.mem.eql(u8, suite_name, "metadata")) continue;
            try names.append(b.allocator, try b.allocator.dupe(u8, suite_name));
        }
    }

    const lessThan = struct {
        fn cmp(_: void, a: []const u8, b_val: []const u8) bool {
            return std.mem.order(u8, a, b_val) == .lt;
        }
    }.cmp;
    std.mem.sort([]const u8, names.items, {}, lessThan);

    var out: std.ArrayListUnmanaged(u8) = .{};
    defer out.deinit(b.allocator);
    try out.appendSlice(b.allocator, "//! Generated by build.zig from test_suite/v1/*.json.gz\n\n");
    try out.appendSlice(b.allocator, "pub const names = [_][]const u8{\n");
    for (names.items) |name| {
        try out.writer(b.allocator).print("    \"{s}\",\n", .{name});
    }
    try out.appendSlice(b.allocator, "};\n");
    return try out.toOwnedSlice(b.allocator);
}

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});

    const optimize = b.standardOptimizeOption(.{});

    const suite_names_content = generateSuiteNamesZig(b) catch @panic("failed to generate suite names");
    const suite_names_files = b.addWriteFiles();
    const suite_names_source = suite_names_files.add("suite_names.zig", suite_names_content);

    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addImport("suite_names", b.createModule(.{
        .root_source_file = suite_names_source,
    }));

    const exe = b.addExecutable(.{
        .name = "asm-run",
        .root_module = exe_mod,
    });

    _ = b.addModule("interpreter-module", .{
        .root_source_file = b.path("src/module.zig"),
    });

    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);

    run_cmd.step.dependOn(b.getInstallStep());

    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    const exe_unit_tests = b.addTest(.{
        .root_module = exe_mod,
        .target = target,
        .optimize = optimize,
    });
    exe_unit_tests.addIncludePath(b.path("."));

    const run_exe_unit_tests = b.addRunArtifact(exe_unit_tests);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_exe_unit_tests.step);
}
